//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcurrentCalls2.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YourTable
    {
        public string RowKey { get; set; }
        public Nullable<System.Guid> Guid1 { get; set; }
        public Nullable<System.Guid> Guid2 { get; set; }
        public string String1 { get; set; }
        public string String2 { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
    }
}
